version: '3'

services:
  db:
    image: mysql
    container_name: mysql-db
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - '6606:3306'
    volumes:
      - "$HOME/docker_volumes/mysql:/var/lib/mysql"  
        #容器的配置目录挂载到host物理机目录/e/docker/mysql/data/conf  
      - "$HOME/docker_volumes/conf/mysql:/etc/mysql/conf.d"